auction_items = [
    "Weekend getaway package",
    "Cooking class with a local chef",
    "Signed guitar by a famous musician",
    "Hot air balloon ride for two",
    "Wine-tasting tour for a group",
    "Skydiving experience",
    "Private tour of a historical site",
    "VIP concert tickets",
    "Personalized jewelry",
    "Rare collectible comic book",
    "Helicopter tour of the city",
    "Sailing lesson for beginners",
    "Custom portrait painting",
    "Spa day package",
    "Autographed sports jersey",
    "Horseback riding lessons",
    "Gourmet dinner for two",
    "Movie night at home package",
    "Membership to a wine club",
    "Private dance lesson",
    "Tickets to a Broadway show",
    "Luxury picnic experience",
    "Virtual reality headset",
    "Custom quilt or blanket",
    "Handmade pottery set",
    "Photography session",
    "Golf outing with a pro",
    "Paint-and-sip night",
    "Guided kayaking trip",
    "Personalized cutting board",
    "Garden consultation service",
    "Antique typewriter",
    "Subscription box (books, coffee, etc.)",
    "Surfing lesson package",
    "Rare vintage records",
    "Pet photoshoot session",
    "Scuba diving experience",
    "Private cooking lesson",
    "Fitness trainer sessions",
    "Camping gear bundle",
    "High-end fishing equipment",
    "Custom-made candle set",
    "Private yacht cruise",
    "Autographed book by a famous author",
    "Guided mountain hike",
    "Online masterclass subscription",
    "Handmade leather wallet",
    "Exclusive wine pairing dinner",
    "Car detailing service",
    "Theater subscription",
    "Craft beer-making kit",
    "Handcrafted wood furniture",
    "Landscape photography print",
    "Fitness tracker",
    "Personalized whiskey glasses",
    "Traditional Japanese tea set",
    "Indoor plant collection",
    "Art supplies gift basket",
    "Electric bike rental",
    "Membership to a botanical garden",
    "High-end luggage set",
    "Yoga class package",
    "Framed vintage map",
    "Professional massage therapy",
    "Personalized passport cover",
    "Culinary tour of a city",
    "Signed movie poster",
    "Art museum membership",
    "Eco-friendly picnic set",
    "Cooking equipment bundle",
    "Luxury bed linens",
    "Acoustic guitar",
    "Online language course",
    "Museum of Modern Art membership",
    "Espresso machine",
    "Personalized recipe book",
    "Tickets to a comedy show",
    "Exclusive beer tasting",
    "Custom pet portrait",
    "Local food tour",
    "Private wine cellar tour",
    "Limited edition board game",
    "Authentic kimono",
    "Home theater projector",
    "Indoor rock climbing passes",
    "Local artist’s painting",
    "Handmade soap and skincare set",
    "Annual zoo membership",
    "Fine dining gift card",
    "Paddleboard rental",
    "Subscription to streaming service",
    "Monogrammed bathrobe",
    "Dance class package",
    "Dinner with a celebrity chef",
    "Luxury car rental for a weekend",
    "Custom leather backpack",
    "Virtual museum tour",
    "Rare wine bottle collection",
    "Personal training session",
    "Golf club membership",
    "Wine tour",
    "Exclusive chocolate tasting",
    "High-quality camping gear set",
    "Signed sports memorabilia",
    "VIP movie screening tickets",
    "Weekend pass to a music festival",
    "Luxury watch",
    "Exotic cooking spices collection",
    "Virtual gaming session with a pro",
    "Cooking tools bundle",
    "Day trip on a sailboat",
    "Personalized stationery set",
    "High-end perfume collection",
    "Pet grooming gift card",
    "Limited edition art print",
    "Local farm-to-table dinner",
    "Pottery class voucher",
    "Antique record player",
    "Personalized luggage tags",
    "Wine-tasting set with glasses",
    "Adventure park tickets",
    "Rare coins collection",
    "Custom engraved necklace",
    "Luxury skincare set",
    "Box of vintage postcards",
    "Outdoor cinema experience",
    "Designer handbag",
    "Historical building tour",
    "Barista training session",
    "High-end painting supplies",
    "Concert tickets package",
    "VIP access to a sports event",
    "Farm fresh produce delivery",
    "Exclusive art gallery tour",
    "Exclusive vineyard tour",
    "Guided city food tour",
    "Craft spirits tasting kit",
    "Personalized family cookbook",
    "Sports Jersey of Your Choice",
    "Artisan coffee brewing kit",
    "Antique mirror",
    "One-year gym membership",
    "Kayak rental for two",
    "Luxury scented candle set",
    "Private zoo tour",
    "Behind-the-scenes museum tour",
    "Luxury silk scarf",
    "Historical re-enactment experience"
]
